### ISSUE TITLE
AbstractAccessSubscriber delivers initial empty items to the subscribers

### ISSUE THREAD

**Issue by slux83** [dariol83/reatmetric#2]
The method `eu.dariolucia.reatmetric.core.impl.managers.AbstractAccessSubscriber#runDistribution()` gets the initial items that match the given filter (at subscription initialization) from the underling processing model and even if the list is empty it gets delivered to the subscribers. This should be avoided.

Attached a simple patch.
[issue_2.patch.txt](https://github.com/dariol83/reatmetric/files/5801173/issue_2.patch.txt)

**Comment by dariol83** [comment]
Fix implemented
