### ISSUE TITLE
ActivityOccurrenceProcessor makes a copy of the reports that is not necessary (double copy)

### ISSUE THREAD

**Issue by slux83** [dariol83/reatmetric#3]
Hi,

the method `eu.dariolucia.reatmetric.processing.impl.processors.ActivityOccurrenceProcessor#generateReport()` creates the `ActivityOccurrenceReport` copying the _this.reports_, but this is already done in the constructor of the `ActivityOccurrenceReport`. 

Attached the small patch.
[issue_3.patch.txt](https://github.com/dariol83/reatmetric/files/5816848/issue_3.patch.txt)

**Comment by dariol83** [comment]
Fix implemented
